/*
  # Create Scales Table

  1. New Tables
    - `scales`
      - `id` (uuid, primary key) - Unique identifier for each scale
      - `name` (text) - Name of the scale (e.g., "DO MIXOLÍDIO", "SI MENOR")
      - `type` (text) - Type of scale (mixolidio or menor)
      - `notes` (text) - Notes in the scale
      - `exercise` (text) - Exercise pattern
      - `lick` (text) - Lick pattern
      - `dominantes` (text) - Dominant notes (optional)
      - `lick_inicio` (text) - Starting lick
      - `lick_final` (text) - Ending lick
      - `order_index` (integer) - Order in the list
      - `created_at` (timestamptz) - Creation timestamp
      - `updated_at` (timestamptz) - Last update timestamp
      - `is_ai_generated` (boolean) - Whether the scale was generated by AI

  2. Security
    - Enable RLS on `scales` table
    - Add policy for public read access (anyone can view scales)
    - Add policy for authenticated users to insert scales
*/

CREATE TABLE IF NOT EXISTS scales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL CHECK (type IN ('mixolidio', 'menor')),
  notes text NOT NULL,
  exercise text NOT NULL,
  lick text NOT NULL,
  dominantes text DEFAULT '',
  lick_inicio text NOT NULL,
  lick_final text NOT NULL,
  order_index integer DEFAULT 0,
  is_ai_generated boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE scales ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read scales"
  ON scales
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert scales"
  ON scales
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update scales"
  ON scales
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete scales"
  ON scales
  FOR DELETE
  TO authenticated
  USING (true);

CREATE INDEX IF NOT EXISTS scales_order_index_idx ON scales(order_index);
CREATE INDEX IF NOT EXISTS scales_type_idx ON scales(type);
